language: java
sudo: false # faster builds

env:
  global:
    - CODECOV_TOKEN="2aa99382-9ca3-4971-a144-628bc1689050" # not required but to be sure

after_success:
  - bash <(curl -s https://codecov.io/bash)